export type CulturalBridge = { workId: string; title: string; medium: "CINE" | "LITERATURA" | "MUSICA" | "ARTE" | "HISTORIA"; humanTension: string; conceptIds: readonly string[]; questionIds: readonly string[]; historicalContext?: string; legalClaimRefs?: readonly string[]; relatedLearning: readonly string[]; culturalSource: string };
export const culturalBridges: readonly CulturalBridge[] = [
 { workId: "film-12-angry-men", title: "12 Angry Men", medium: "CINE", humanTension: "Decidir con información incompleta y presión social.", conceptIds: ["prueba", "hecho-juridicamente-relevante"], questionIds: ["¿Qué diferencia hay entre sospechar y sostener un hecho?"], relatedLearning: ["organizar-hechos-y-prueba"], culturalSource: "Obra cinematográfica de 1957; referencia cultural, no fuente jurídica." },
 { workId: "literature-the-trial", title: "The Trial", medium: "LITERATURA", humanTension: "Una persona frente a un proceso opaco.", conceptIds: ["prueba", "obligacion"], questionIds: ["¿Qué debe poder entender alguien cuando una institución decide?"], relatedLearning: ["organizar-hechos-y-prueba"], culturalSource: "Novela de Franz Kafka; referencia cultural, no fuente jurídica." },
 { workId: "literature-antigone", title: "Antígona", medium: "LITERATURA", humanTension: "Conflicto entre norma, autoridad y conciencia.", conceptIds: ["obligacion", "conducta"], questionIds: ["¿Cuándo obedecer una regla no resuelve el conflicto humano?"], historicalContext: "Tragedia griega atribuida a Sófocles.", relatedLearning: ["consentimiento-y-obligaciones"], culturalSource: "Obra literaria clásica; referencia cultural, no fuente jurídica." },
 { workId: "literature-pride-prejudice", title: "Pride and Prejudice", medium: "LITERATURA", humanTension: "Reputación, promesa y expectativa.", conceptIds: ["consentimiento", "obligacion"], questionIds: ["¿Qué se dijo, qué se aceptó y qué se puede demostrar?"], relatedLearning: ["leer-antes-de-aceptar"], culturalSource: "Novela de Jane Austen; referencia cultural, no fuente jurídica." },
 { workId: "film-social-network", title: "The Social Network", medium: "CINE", humanTension: "Acuerdos, autoría y memoria de una relación.", conceptIds: ["prueba", "representacion"], questionIds: ["¿Qué prueba la historia de una conversación o acuerdo?"], relatedLearning: ["organizar-hechos-y-prueba"], culturalSource: "Obra cinematográfica de 2010; referencia cultural, no fuente jurídica." },
 { workId: "music-strange-fruit", title: "Strange Fruit", medium: "MUSICA", humanTension: "Memoria, violencia y dignidad pública.", conceptIds: ["conducta", "hecho-juridicamente-relevante"], questionIds: ["¿Cómo cambia una pregunta cuando una historia colectiva exige ser nombrada?"], relatedLearning: ["organizar-hechos-y-prueba"], culturalSource: "Canción interpretada por Billie Holiday; referencia cultural, no fuente jurídica." },
 { workId: "art-guernica", title: "Guernica", medium: "ARTE", humanTension: "Violencia, representación y memoria.", conceptIds: ["hecho-juridicamente-relevante", "prueba"], questionIds: ["¿Qué puede hacer visible una imagen sin probar por sí sola un hecho?"], relatedLearning: ["organizar-hechos-y-prueba"], culturalSource: "Pintura de Pablo Picasso; referencia cultural, no fuente jurídica." },
 { workId: "history-magna-carta", title: "Magna Carta", medium: "HISTORIA", humanTension: "Límites al poder y promesas institucionales.", conceptIds: ["obligacion", "representacion"], questionIds: ["¿Cómo se construyen límites cuando el poder actúa por instituciones?"], historicalContext: "Carta de 1215; contexto histórico, no regla universal vigente.", relatedLearning: ["empresa-que-obliga"], culturalSource: "Documento histórico; referencia cultural, no fuente jurídica actual." },
] as const;
export function validateCulturalBridges() { return culturalBridges.every((bridge) => bridge.culturalSource.includes("no fuente jurídica") && bridge.conceptIds.length > 0 && bridge.relatedLearning.length > 0); }
