export type AtlasEntry = {
  id: string;
  kind: "CINE" | "LITERATURA" | "FILOSOFIA" | "TECNOLOGIA";
  reference: string;
  workContext: string;
  conduct: string;
  conflict: string;
  rule: string;
  limit: string;
  sourceLabel: string;
  sourceUrl: string;
  sourceArticles: string;
  questions: [string, string, string];
  routeCandidate: string;
  visualWorld: string;
  visualSchool: string;
  framing: string;
  status: "INTERNAL_REVIEW_ONLY";
};

export const culturalAtlas: AtlasEntry[] = [
  {
    id: "social-network-dilution",
    kind: "CINE",
    reference: "The Social Network",
    workContext: "La disputa entre cofundadores por participación, control y aumentos de capital.",
    conduct: "Diluir la participación de un socio mediante una emisión asimétrica de nuevas acciones.",
    conflict: "Derechos de preferencia, deberes de administradores y abuso de mayorías.",
    rule: "Una ampliación de capital debe analizarse junto con el tipo social, los estatutos, las mayorías y los derechos de suscripción aplicables.",
    limit: "La obra cinematográfica no prueba los hechos de una sociedad real ni permite concluir que una operación concreta sea abusiva.",
    sourceLabel: "Ley General de Sociedades Mercantiles",
    sourceUrl: "https://www.diputados.gob.mx/LeyesBiblio/pdf/LGSM.pdf",
    sourceArticles: "LGSM Art. 132 · texto y vigencia por verificar antes de publicación",
    questions: ["¿Qué tipo de sociedad y estatutos gobiernan la emisión?", "¿Hubo convocatoria y quórum verificables?", "¿El socio recibió oportunidad real de suscribir?"],
    routeCandidate: "/pacto-de-socios/ · FUTURA / BLOQUEADA",
    visualWorld: "corporate_archive",
    visualSchool: "documentary_tension",
    framing: "split_control_room",
    status: "INTERNAL_REVIEW_ONLY",
  },
  {
    id: "merchant-of-venice-penalty",
    kind: "LITERATURA",
    reference: "El Mercader de Venecia",
    workContext: "Una deuda literaria se asegura mediante una penalización que invade la integridad física.",
    conduct: "Pactar una prestación extrema como consecuencia del incumplimiento.",
    conflict: "Autonomía de la voluntad, pena convencional, derechos indisponibles y orden público.",
    rule: "La libertad contractual tiene límites: una penalización debe analizarse por su objeto, proporción, licitud y compatibilidad con derechos indisponibles.",
    limit: "La lectura literaria no sustituye el análisis del contrato, la jurisdicción, la obligación principal ni la conducta posterior de las partes.",
    sourceLabel: "Código Civil Federal",
    sourceUrl: "https://www.diputados.gob.mx/LeyesBiblio/pdf/CCF.pdf",
    sourceArticles: "CCF Arts. 8 y 1843 · texto y alcance por verificar antes de publicación",
    questions: ["¿La pena excede la obligación principal?", "¿La cláusula afecta un derecho indisponible?", "¿Qué remedio lícito queda para el incumplimiento?"],
    routeCandidate: "/clausula-penal/ · FUTURA / BLOQUEADA",
    visualWorld: "theatre_contract",
    visualSchool: "material_symbolism",
    framing: "single_object_closeup",
    status: "INTERNAL_REVIEW_ONLY",
  },
  {
    id: "godfather-coercion",
    kind: "CINE",
    reference: "The Godfather",
    workContext: "Una oferta presentada como imposible de rechazar altera la libertad de decisión.",
    conduct: "Obtener aceptación mediante amenaza, intimidación o presión grave.",
    conflict: "Consentimiento, violencia, intimidación y validez del contrato.",
    rule: "La existencia de una firma no resuelve por sí sola si el consentimiento fue libre ni si hubo violencia o intimidación jurídicamente relevante.",
    limit: "La ficción dramatiza la amenaza; una valoración real exige hechos, contexto, personas, mensajes y prueba.",
    sourceLabel: "Código Civil Federal",
    sourceUrl: "https://www.diputados.gob.mx/LeyesBiblio/pdf/CCF.pdf",
    sourceArticles: "CCF Arts. 1818 y 1819 · texto y alcance por verificar antes de publicación",
    questions: ["¿Qué amenaza concreta se comunicó?", "¿A quién afectaba y qué riesgo era previsible?", "¿Qué ocurrió antes y después de la firma?"],
    routeCandidate: "/consentimiento-bajo-presion/ · FUTURA / BLOQUEADA",
    visualWorld: "private_room",
    visualSchool: "cinematic_pressure",
    framing: "threshold_portrait",
    status: "INTERNAL_REVIEW_ONLY",
  },
  {
    id: "succession-trust-control",
    kind: "CINE",
    reference: "Succession",
    workContext: "Una familia empresarial disputa el control de un fideicomiso y de sus órganos de decisión.",
    conduct: "Intentar modificar reglas de control o voto sin comprobar el acto constitutivo y las mayorías requeridas.",
    conflict: "Gobierno corporativo, fideicomiso, derechos de beneficiarios y acuerdos familiares.",
    rule: "El efecto de una modificación depende del texto constitutivo, la calidad de las partes, las facultades y las formalidades aplicables.",
    limit: "Una serie no demuestra que un fideicomiso real sea irrevocable ni que exista consentimiento unánime.",
    sourceLabel: "Ley General de Títulos y Operaciones de Crédito",
    sourceUrl: "https://www.diputados.gob.mx/LeyesBiblio/pdf/145_220324.pdf",
    sourceArticles: "LGTOC Art. 391 · texto y aplicación por verificar antes de publicación",
    questions: ["¿Qué dice literalmente el acto constitutivo?", "¿Quién puede modificar o remover al fiduciario?", "¿El protocolo familiar es vinculante o declarativo?"],
    routeCandidate: "/gobierno-familiar/ · FUTURA / BLOQUEADA",
    visualWorld: "boardroom_archive",
    visualSchool: "power_geometry",
    framing: "empty_chair_table",
    status: "INTERNAL_REVIEW_ONLY",
  },
  {
    id: "twelve-angry-men-doubt",
    kind: "CINE",
    reference: "12 Angry Men",
    workContext: "Un grupo debe decidir si la prueba y los prejuicios permiten sostener una condena.",
    conduct: "Condenar sin contrastar evidencia, hipótesis alternativas y estándar de prueba.",
    conflict: "Presunción de inocencia, valoración probatoria y duda razonable.",
    rule: "La valoración de prueba requiere distinguir hechos demostrados, inferencias y prejuicios; el estándar depende del sistema y procedimiento aplicables.",
    limit: "No se debe trasladar automáticamente una regla cinematográfica a un expediente real ni a una jurisdicción distinta.",
    sourceLabel: "Constitución Política de los Estados Unidos Mexicanos",
    sourceUrl: "https://www.diputados.gob.mx/LeyesBiblio/pdf/CPEUM.pdf",
    sourceArticles: "CPEUM Art. 20 · texto y alcance por verificar antes de publicación",
    questions: ["¿Qué hecho debe probarse exactamente?", "¿Qué evidencia es directa y cuál es inferencial?", "¿Qué alternativa razonable no ha sido contrastada?"],
    routeCandidate: "/organizar-hechos-y-prueba/ · RUTA EXISTENTE",
    visualWorld: "jury_room",
    visualSchool: "analytical_ensemble",
    framing: "tabletop_evidence",
    status: "INTERNAL_REVIEW_ONLY",
  },
  {
    id: "trial-opacity",
    kind: "LITERATURA",
    reference: "El Proceso",
    workContext: "Una persona enfrenta una acusación opaca sin comprender el hecho, la autoridad o el expediente.",
    conduct: "Detener, juzgar o afectar derechos sin informar con claridad la acusación y el procedimiento.",
    conflict: "Audiencia, legalidad, defensa adecuada, acceso al expediente y motivación.",
    rule: "La autoridad y el procedimiento deben analizarse por competencia, fundamento, motivación, comunicación y oportunidad de defensa.",
    limit: "La metáfora kafkiana no identifica por sí sola una violación en un acto administrativo o judicial concreto.",
    sourceLabel: "Constitución Política de los Estados Unidos Mexicanos",
    sourceUrl: "https://www.diputados.gob.mx/LeyesBiblio/pdf/CPEUM.pdf",
    sourceArticles: "CPEUM Arts. 14 y 16 · CADH Art. 8 · texto y alcance por verificar",
    questions: ["¿Qué autoridad emitió el acto y con qué competencia?", "¿Qué hechos y normas se comunicaron?", "¿Existe acceso suficiente al expediente?"],
    routeCandidate: "/verificar-autoridad/ · FUTURA / BLOQUEADA",
    visualWorld: "bureaucratic_corridor",
    visualSchool: "architectural_absurdity",
    framing: "long_corridor",
    status: "INTERNAL_REVIEW_ONLY",
  },
  {
    id: "erin-brockovich-environment",
    kind: "CINE",
    reference: "Erin Brockovich",
    workContext: "Una comunidad enfrenta contaminación, daños y ocultamiento de información científica.",
    conduct: "Contaminar, ocultar reportes o impedir que una comunidad conozca un riesgo ambiental.",
    conflict: "Daño ambiental, causalidad, prueba científica, reparación y acciones colectivas.",
    rule: "Una afirmación de responsabilidad ambiental exige conectar conducta, daño, causalidad, evidencia y régimen aplicable.",
    limit: "La dramatización no prueba causalidad ni responsabilidad de una empresa real.",
    sourceLabel: "Ley Federal de Responsabilidad Ambiental",
    sourceUrl: "https://www.diputados.gob.mx/LeyesBiblio/pdf/LFRA.pdf",
    sourceArticles: "Ley Federal de Responsabilidad Ambiental · texto y vigencia por verificar",
    questions: ["¿Qué contaminante y qué daño están documentados?", "¿Qué evidencia conecta fuente, exposición y daño?", "¿Qué acción y territorio son procedentes?"],
    routeCandidate: "/mapa-de-dano-ambiental/ · FUTURA / BLOQUEADA",
    visualWorld: "water_table",
    visualSchool: "scientific_trace",
    framing: "wide_landscape",
    status: "INTERNAL_REVIEW_ONLY",
  },
  {
    id: "ai-authorship",
    kind: "TECNOLOGIA",
    reference: "IA generativa y autoría humana",
    workContext: "Una persona usa un modelo generativo y quiere atribuirse o registrar el resultado.",
    conduct: "Generar una obra con IA y tratar el resultado como si toda la autoría humana fuera evidente.",
    conflict: "Autoría, intervención creativa, selección, edición, licencias y prueba del proceso.",
    rule: "La protección y atribución deben analizar el grado de intervención humana, la obra concreta, el territorio y las reglas de la plataforma.",
    limit: "No se debe afirmar dominio público, registro o protección automática sin verificar jurisdicción, obra, proceso y criterio vigente.",
    sourceLabel: "INDAUTOR / fuente de trabajo pendiente",
    sourceUrl: "https://www.indautor.gob.mx/",
    sourceArticles: "Criterio territorial pendiente de cotejo literal",
    questions: ["¿Qué parte fue seleccionada, editada o creada por una persona?", "¿Se conservan versiones y registros del proceso?", "¿Qué licencia impone la herramienta usada?"],
    routeCandidate: "/autoría-y-ia/ · FUTURA / BLOQUEADA",
    visualWorld: "creator_studio",
    visualSchool: "process_documentary",
    framing: "layers_and_hands",
    status: "INTERNAL_REVIEW_ONLY",
  },
  {
    id: "digital-inheritance",
    kind: "TECNOLOGIA",
    reference: "Herencia digital",
    workContext: "Una persona fallece dejando cuentas, activos digitales y archivos sin instrucciones claras.",
    conduct: "Intentar acceder o transmitir cuentas y activos digitales sin separar patrimonio, privacidad y términos de servicio.",
    conflict: "Sucesión, activos patrimoniales, privacidad, secreto de comunicaciones y proveedores transfronterizos.",
    rule: "El análisis debe separar el valor patrimonial del acceso a comunicaciones privadas y de las reglas contractuales de cada plataforma.",
    limit: "Una cuenta no equivale automáticamente a un activo transmisible ni el heredero tiene acceso irrestricto a datos de terceros.",
    sourceLabel: "Código Civil Federal · referencia de trabajo",
    sourceUrl: "https://www.diputados.gob.mx/LeyesBiblio/pdf/CCF.pdf",
    sourceArticles: "CCF Art. 1281 · legislación local y términos de servicio por verificar",
    questions: ["¿Qué activos tienen valor patrimonial demostrable?", "¿Existe voluntad digital o designación de contacto?", "¿Qué datos de terceros quedarían expuestos?"],
    routeCandidate: "/herencia-digital/ · FUTURA / BLOQUEADA",
    visualWorld: "cloud_archive",
    visualSchool: "quiet_forensics",
    framing: "sealed_devices",
    status: "INTERNAL_REVIEW_ONLY",
  },
  {
    id: "pacta-rebus",
    kind: "FILOSOFIA",
    reference: "Pacta sunt servanda · rebus sic stantibus",
    workContext: "Un acuerdo debe cumplirse, pero una alteración extraordinaria puede romper el equilibrio esperado.",
    conduct: "Exigir el cumplimiento literal de un contrato pese a un cambio radical de circunstancias.",
    conflict: "Fuerza obligatoria, imprevisión, equilibrio contractual y renegociación.",
    rule: "La fuerza del contrato debe leerse junto con las reglas de modificación, riesgo, buena fe y remedios aplicables al territorio.",
    limit: "Una crisis económica o personal no produce automáticamente renegociación ni resolución.",
    sourceLabel: "Código Civil Federal · referencia de trabajo",
    sourceUrl: "https://www.diputados.gob.mx/LeyesBiblio/pdf/CCF.pdf",
    sourceArticles: "CCF Art. 1796 · texto y doctrina aplicable por verificar",
    questions: ["¿Qué circunstancia cambió y cuándo?", "¿Quién asumió contractualmente ese riesgo?", "¿Qué remedio prevé el contrato o la ley?"],
    routeCandidate: "/contrato-en-crisis/ · FUTURA / BLOQUEADA",
    visualWorld: "weathered_contract",
    visualSchool: "temporal_documentary",
    framing: "folded_timeline",
    status: "INTERNAL_REVIEW_ONLY",
  },
];

export const culturalAtlasMeta = {
  title: "Atlas Ejecutivo de Vinculación Total",
  subtitle: "Cultura, cine, literatura, filosofía y vida contemporánea conectadas al Derecho",
  status: "INTERNAL_REVIEW_ONLY",
  note: "Las referencias culturales son puertas de entrada. La regla jurídica, el territorio, la vigencia y el límite requieren cotejo antes de cualquier publicación.",
};
